name: brain_flower
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^1.1.1
  flutter_svg: ^0.17.3+1
  auto_size_text: ^2.1.0
  collection: ^1.14.11
  # Streams
  rxdart: ^0.23.1
  # Service Locator
  get_it: ^4.0.2
  injectable: ^0.4.0
  # Animations
  flare_flutter: ^2.0.3
  # Shared Preferences
  shared_preferences: ^0.5.7+2
  # Bloc
  flutter_bloc: ^4.0.1
  # Database
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # Navigation
  auto_route: ^0.5.0
  # Data Classes
  freezed_annotation:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mockito: ^4.1.1
  hive_generator: ^0.7.0+2
  freezed: ^0.11.2
  injectable_generator: ^0.4.0+1
  auto_route_generator: ^0.5.0

dependency_overrides:
  dartx: ^0.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/